name: Notify Slack for Old PRs

on:
  schedule:
    - cron: "0 * * * *"
    - cron: "5 * * * *"
    - cron: "10 * * * *"
    - cron: "15 * * * *"
    - cron: "20 * * * *"
    - cron: "25 * * * *"
    - cron: "30 * * * *"
    - cron: "35 * * * *"
    - cron: "40 * * * *"
    - cron: "45 * * * *"
    - cron: "50 * * * *"
    - cron: "55 * * * *"

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get old pull requests
        id: get-old-prs
        run: |
          echo "Pull requests that are older than 1 minute:"
          pr_list=$(gh pr list --state open --json createdAt,number,title,url --jq '.[] | select(.createdAt < "'$(date --date="1 minute ago" --iso-8601=seconds)'") | .createdAt = (.createdAt | fromdate | strftime("%Y/%m/%d %H:%M") | gsub(" "; "T") | . + "+09:00" | strptime("%Y-%m-%dT%H:%M%z") | strftime("%Y/%m/%d %H:%M"))')
          echo "::set-output name=pr_list::$pr_list"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send message to Slack if PRs exist
        if: steps.get-old-prs.outputs.pr_list
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "古いプルリクエストのリスト:\n${{ steps.get-old-prs.outputs.pr_list }}\nこちらのプルリクエストを確認してください。"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send message to Slack if no PRs
        if: steps.get-old-prs.outputs.pr_list == ''
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "古いプルリクエストはありません。"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
