name: Notify Slack for Old PRs

on:
  schedule:
    - cron: "30 16 * * *" # 毎日午前13時に実行

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Hello World to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "Hello World"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
