name: Notify Slack for Old PRs

on:
  schedule:
    - cron: "40 23 * * *"
    - cron: "45 23 * * *"
    - cron: "50 23 * * *"
    - cron: "55 23 * * *"
    - cron: "0 0 * * *"
    - cron: "10 0 * * *"
    - cron: "20 0 * * *"
    - cron: "30 0 * * *"
    - cron: "40 0 * * *"

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get old pull requests
        id: get-old-prs
        run: |
          echo "Pull requests that are older than 1 minute:"
          pr_list=$(gh pr list --state open --json createdAt,number,title,url --jq '.[] | select(.createdAt < "'$(date --date="1 minute ago" --iso-8601=seconds)'")')
          echo "::set-output name=pr_list::$pr_list"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send message to Slack
        if: steps.get-old-prs.outputs.pr_list
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: "古いプルリクエストのリスト: ${{ steps.get-old-prs.outputs.pr_list }} こちらのプルリクエストを確認してください。"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
