name: Notify Slack for Old PRs

on:
  schedule:
    - cron: "0 * * * *"
    - cron: "30 * * * *"

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get old pull requests
        id: get-old-prs
        run: |
          echo "Pull requests that are older than 1 minute for the 'master' or 'develop' branches:"
          pr_list_master=$(gh pr list --base master --state open --json createdAt,title,url --jq '.[] | select(.createdAt < "'$(date --date="1 minute ago" --iso-8601=seconds)'") | .createdAt = "作成日時: " + (.createdAt | fromdate | strftime("%Y-%m-%d %H:%M") | gsub(" "; "T") | . + "+09:00" | strptime("%Y-%m-%dT%H:%M%z") | strftime("%Y-%m-%d %H:%M")) | "[\(.title)](\(.url)) - \(.createdAt)\n"')
          pr_list_develop=$(gh pr list --base develop --state open --json createdAt,title,url --jq '.[] | select(.createdAt < "'$(date --date="1 minute ago" --iso-8601=seconds)'") | .createdAt = "作成日時: " + (.createdAt | fromdate | strftime("%Y-%m-%d %H:%M") | gsub(" "; "T") | . + "+09:00" | strptime("%Y-%m-%dT%H:%M%z") | strftime("%Y-%m-%d %H:%M")) | "[\(.title)](\(.url)) - \(.createdAt)\n"')
          combined_pr_list="$pr_list_master$pr_list_develop"
          echo "::set-output name=pr_list::$combined_pr_list"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Send message to Slack if PRs exist
        if: steps.get-old-prs.outputs.pr_list
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "【1週間経過したPR】\n${{ steps.get-old-prs.outputs.pr_list }}\n"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send message to Slack if no PRs
        if: steps.get-old-prs.outputs.pr_list == ''
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "古いプルリクエストはありません。"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
