name: Notify Slack for Old PRs

on:
  schedule:
    - cron: "0 * * * *"
    - cron: "5 * * * *"
    - cron: "10 * * * *"
    - cron: "15 * * * *"
    - cron: "20 * * * *"
    - cron: "25 * * * *"
    - cron: "30 * * * *"
    - cron: "35 * * * *"
    - cron: "40 * * * *"
    - cron: "45 * * * *"
    - cron: "50 * * * *"
    - cron: "55 * * * *"

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get old pull requests
        id: get-old-prs
        run: |
          PR_LIST=$(gh pr list --limit 10 --json title,url,createdAt --search "is:draft:false")
          echo "Open pull requests:"
          echo "$PR_LIST"
          PR_LIST_ESCAPED=$(echo "$PR_LIST" | jq -r '.[] | "\(.title) \((.createdAt | fromdateiso8601 | . + 32400 | todateiso8601)) \(.url) (経過日数: \((now - (.createdAt | fromdateiso8601)) / 86400 | floor)日)"' | sed ':a;N;$!ba;s/\n/%0A/g')
          echo "::set-output name=pr_list::$PR_LIST_ESCAPED"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send message to Slack if PRs exist
        if: steps.get-old-prs.outputs.pr_list
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "${{ github.repository }} \n【1週間経過したPR】\n${{ steps.get-old-prs.outputs.pr_list }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send message to Slack if no PRs
        if: steps.get-old-prs.outputs.pr_list == ''
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: "古いプルリクエストはありません。"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
